name: plotexci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Dependency packages
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential python3 npm
    - name: make
      run: make
